package com.maan.veh.claim.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.maan.veh.claim.request.GarageWorkOrderRequest;
import com.maan.veh.claim.response.CommonResponse;
import com.maan.veh.claim.response.GarageWorkOrderSaveReq;
import com.maan.veh.claim.service.GarageWorkOrderService;

import io.swagger.v3.oas.annotations.Operation;

@RestController
@RequestMapping("/workOrder")
public class GarageWorkOrderController {

    @Autowired
    private GarageWorkOrderService service;

    @Operation(summary = "Save a garage work order", 
    	    description = "This endpoint is used to save a new work order for a garage and update that work order. \n\n"
    	        + "***Details:*** \n"
    	        + "1. For creating new work order, send the ***quotation number as NULL.*** \n"
    	        + "2. The quotation number will be auto-generated by the system and returned in the response. \n"
    	        + "3. For updating the work order, send the ***claim number and quotation number.*** \n"
    	        + "4. All types of users (Garage, Surveyor, Dealer) will use this API to save or update the work order. \n"
    	        + "5. In the ***status*** column of the ***work order table***, the ***UserType*** is saved for identification. \n"
    	        + "6. The ***status*** column of the ***vehicle info*** table is updated with the current ***quote status*** in the end."
    	)
    @PostMapping("/garage/save")
    public ResponseEntity<CommonResponse> saveWorkOrder(@RequestBody GarageWorkOrderSaveReq claim) {
    	CommonResponse savedClaim = service.saveWorkOrder(claim);
    	return new ResponseEntity<>(savedClaim, HttpStatus.OK);
    }


    @Operation(summary = "Get work orders by claim number", description = "Fetches garage work orders based on the provided claim number.")
    @PostMapping("/garage/view")
    public ResponseEntity<CommonResponse> getGarageWorkOrdersByClaimNo(@RequestBody GarageWorkOrderRequest request) {
        CommonResponse response = service.getGarageWorkOrdersByClaimNo(request);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    @Operation(summary = "Get work orders by garage", description = "Retrieves all garage work orders based on the garage information.")
    @PostMapping("/getAllByGarage")
    public ResponseEntity<CommonResponse> getGarageWorkOrders(@RequestBody GarageWorkOrderRequest request) {
        CommonResponse response = service.getGarageWorkOrders(request);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    @Operation(summary = "Get all garage work orders", description = "Fetches all garage work orders based on the provided request.")
    @PostMapping("/getAll")
    public ResponseEntity<CommonResponse> getAllGarageWorkOrders(@RequestBody GarageWorkOrderRequest request) {
        CommonResponse response = service.getAllGarageWorkOrders(request);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }
    
    @PostMapping("/surveyor/assign")
    public ResponseEntity<CommonResponse> assignWorkOrder(@RequestBody GarageWorkOrderSaveReq claim) {
    	CommonResponse savedClaim = service.saveWorkOrder(claim);
    	return new ResponseEntity<>(savedClaim, HttpStatus.OK);
    }
    
    @PostMapping("/surveyor/view")
    public ResponseEntity<CommonResponse> surveyorViewGarageWorkOrdersByClaimNo(@RequestBody GarageWorkOrderRequest request) {
        CommonResponse response = service.getGarageWorkOrdersByClaimNo(request);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }
}
