/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.veh.claim.controller;


import java.util.Collections;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.maan.veh.claim.dto.Menu;
import com.maan.veh.claim.request.MenuListReq;
import com.maan.veh.claim.response.CommonRes;
import com.maan.veh.claim.service.LoginDetailsService;


/**
* <h2>LoginMasterController</h2>
*/
@RestController
@RequestMapping("/admin")
public class LoginDetailsController {

	@Autowired
	private  LoginDetailsService entityService;
	
	@PostMapping("/getmenulist")
	public ResponseEntity<CommonRes> getBrokerLoginDetailsSubUserType(@RequestBody  MenuListReq req) {

		CommonRes data = new CommonRes();
		
		/////// grid
		List<Menu>  res = entityService.getMenuList(req);
		data.setCommonResponse(res);
		data.setIsError(false);
		data.setErrorMessage(Collections.emptyList());
		data.setMessage("Success");
		if (res != null) {
			return new ResponseEntity<CommonRes>(data, HttpStatus.CREATED);
		} else {
			return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
		}
	}
	
}