/*
 * Java domain class for entity "ClaimLosstypeMaster" 
 * Created on 2021-07-31 ( Date ISO 2021-07-31 - Time 18:13:32 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2021-07-31 ( 18:13:32 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.veh.claim.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.veh.claim.entity.ClaimLossTypeMaster;
import com.maan.veh.claim.entity.ClaimLossTypeMasterId;

/**
 * <h2>ClaimLosstypeMasterRepository</h2>
 *
 * createdAt : 2021-07-31 - Time 18:13:32
 * <p>
 * Description: "ClaimLosstypeMaster" Repository
 */

public interface ClaimLosstypeMasterRepository extends JpaRepository<ClaimLossTypeMaster, ClaimLossTypeMasterId>,
		JpaSpecificationExecutor<ClaimLossTypeMaster> {

	List<ClaimLossTypeMaster> findByStatusOrderByCategoryIdAsc(String string);

}
