/*
 * Java domain class for entity "InsuranceCompanyMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.veh.claim.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.veh.claim.entity.InsuranceCompanyMaster;
import com.maan.veh.claim.entity.InsuranceCompanyMasterId;
/**
 * <h2>InsuranceCompanyMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:27
 * <p>
 * Description: "InsuranceCompanyMaster" Repository
 */
 
 
 
public interface InsuranceCompanyMasterRepository  extends JpaRepository<InsuranceCompanyMaster,InsuranceCompanyMasterId > , JpaSpecificationExecutor<InsuranceCompanyMaster> {

	InsuranceCompanyMaster findByCompanyId(String insuranceId);

	List<InsuranceCompanyMaster> findByStatus(String string);


}
