/*
 * Java domain class for entity "VehicleBodypartsMaster" 
 * Created on 2021-08-13 ( Date ISO 2021-08-13 - Time 12:21:07 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2021-08-13 ( 12:21:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.veh.claim.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.veh.claim.entity.VehicleBodypartsMaster;
import com.maan.veh.claim.entity.VehicleBodypartsMasterId;
/**
 * <h2>VehicleBodypartsMasterRepository</h2>
 *
 * createdAt : 2021-08-13 - Time 12:21:07
 * <p>
 * Description: "VehicleBodypartsMaster" Repository
 */
 
 
 
public interface VehicleBodypartsMasterRepository  extends JpaRepository<VehicleBodypartsMaster,VehicleBodypartsMasterId > , JpaSpecificationExecutor<VehicleBodypartsMaster> {

	List<VehicleBodypartsMaster> findByStatusAndCompanyIdOrderByPartIdAsc(String string,BigDecimal comapanyId);

	List<VehicleBodypartsMaster> findByStatusAndPartDescriptionOrderByPartIdAsc(String string, String value);

	

}
