/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:20:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:20:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.veh.claim.entity;


import java.io.Serializable;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;





/**
* Domain class for entity "LoginMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(LoginMasterId.class)
@Table(name="vc_login_master")


public class LoginMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOGIN_ID", nullable=false, length=50)
    private String     loginId ;

    @Id
    @Column(name="USER_TYPE", nullable=false, length=20)
    private String     userType ;


    //--- ENTITY DATA FIELDS 
    @Column(name="PASSWORD", length=100)
    private String     password ;

    @Column(name="COMPANY_ID", length=20)
    private String     companyId ;

    @Column(name="AGENCY_CODE", length=10)
    private String     agencyCode ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="OA_CODE", length=10)
    private Integer     oaCode ;

    @Column(name="LPASS1", length=50)
    private String     lpass1 ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LPASS_DATE")
    private Date       lpassDate ;

    @Column(name="LPASS2", length=50)
    private String     lpass2 ;

    @Column(name="LPASS3", length=50)
    private String     lpass3 ;

    @Column(name="CREATED_BY", length=20)
    private String     createdBy ;
    
    @Column(name="STATUS", nullable=false, length=1)
    private String     status ;

    @Column(name="UPDATED_BY", length=20)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="LPASS4", length=20)
    private String     lpass4 ;

    @Column(name="LPASS5", length=20)
    private String     lpass5 ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="PWD_COUNT", length=10)
    private String     pwdCount ;
    
    @Column(name="CORE_APP_CODE", length=100)
    private String    coreAppCode;

    //--- ENTITY LINKS ( RELATIONSHIP )


}



