/*
 * Created on 2022-01-05 ( 16:11:20 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.veh.claim.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.Getter;
import lombok.Setter;

/**
 * Composite primary key for entity "VehicleBodypartsMaster" ( stored in table "VEHICLE_BODYPARTS_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
public class VehicleBodypartsMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal partId ;
    
    private BigDecimal companyId ;
    
    
     
}
